s/VL_NS_BEGIN//
s/VL_NS_END//
s/VL_V_SUFF(\([^)]*\))/\1i/
s/VL_M_SUFF(\([^)]*\))/\1i/
s/TElt/int/g
s/TVec2/Vec2i/g
s/TVec3/Vec3i/g
s/TVec4/Vec4i/g
s/TMat2/Mat2i/g
s/TMat3/Mat3i/g
s/TMat4/Mat4i/g
/\#include/d
/^\/\*/,/\*\//d
s/VL_VEC\([234]\)_H/VLI_VEC\1_H/g
s/VL_MAT\([234]\)_H/VLI_MAT\1_H/g
s/VL_SWIZZLE_H/VLI_SWIZZLE_H/g
s/VL_PRINT_234_H/VLI_PRINT_234_H/g
s/VL_STREAM_234_H/VLI_STREAM_234_H/g
